# 说明
# 该文件是 uzon-mail 的 docker-compose 配置文件，用于在 linux 中启动程序
# 使用时，需要将该文件放置在 uzon-mail 的根目录下，然后执行 docker-compose up -d 命令即可启动程序
#

version: '3.8'
services:
  # mysql
  mysql:
    container_name: uzon-mysql
    image: mysql:8.4.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root3306
      MYSQL_DATABASE: uzon-mail
      MYSQL_USER: uzon-mail
      MYSQL_PASSWORD: uzon-mail
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    networks:
      - uzon-network

  # redis 缓存
  redis:
    container_name: uzon-redis
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - ./docker/redis/data:/data
    restart: always
    networks:
      - uzon-network

  # 程序主体
  uzon-mail:
    container_name: uzon-mail
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build: . # 使用当前目录下的 Dockerfile 文件构建镜像
    ports:
      - 22345:22345
    volumes:
      - ./docker/uzon-mail/src:/app
    networks:
      - uzon-network
    depends_on:
      - uzon-mysql
      - uzon-redis

networks:
  uzon-network:
    driver: bridge