version: '3.8'

services:
  uzon-mail:
    container_name: 'uzon-mail'
    image: node:lts-bullseye
    volumes:
      - ${SRC}:/app/uzon-mail
    working_dir: /app/uzon-mail
    ports:
      - 9000:9000
    #command: ["sh","-c","npm run dev"]

    # 为容器启动一个轻量级的 init 系统，可以处理孤儿进程并转发信号，解决 stop 速度慢的问题
    init: true
    command: [ "sh", "-c", "exec sleep infinity" ]

  mysql:
    container_name: mysql
    image: mysql:8.4.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root3306
      MYSQL_DATABASE: uzon-mail
      MYSQL_USER: uzon-mail
      MYSQL_PASSWORD: uzon-mail
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
